Start new style rewriting mechanism (use --enable-experimental to test)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -842,6 +842,7 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-fastalloc     omit fast allocator for small objects
+  --enable-experimental   support new style rewriting code
   --enable-debug=ARG      install a debugging enable executable -ggdb
   --enable-warnings       print warning messages during compilation
   --enable-optimize=ARG   compile with optimizations guessed
@@ -6291,6 +6292,41 @@ echo "$as_me: error: bad option --enable-fastalloc=$enable_fastalloc" >&2;}
 esac
 
 #--------------------------------------------------------------------
+# Experimental options
+#--------------------------------------------------------------------
+
+# Check whether --enable-experimental or --disable-experimental was given.
+if test "${enable_experimental+set}" = set; then
+  enableval="$enable_experimental"
+
+else
+  enable_experimental="no"
+fi;
+case "$enable_experimental" in
+    yes)
+	echo "$as_me:$LINENO: result: enabling experimental style rewriting code" >&5
+echo "${ECHO_T}enabling experimental style rewriting code" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define EXPERIMENTAL 1
+_ACEOF
+
+        CONFIG_EXPERIMENTAL="Memorizer Environment Evaluate"
+        ;;
+    no)
+	echo "$as_me:$LINENO: result: disabling experimental features" >&5
+echo "${ECHO_T}disabling experimental features" >&6
+        CONFIG_EXPERIMENTAL=""
+	;;
+    *)
+	{ { echo "$as_me:$LINENO: error: bad option --enable-experimental=$enable_experimental" >&5
+echo "$as_me: error: bad option --enable-experimental=$enable_experimental" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+esac
+
+
+#--------------------------------------------------------------------
 # Debugging options
 #--------------------------------------------------------------------
 
@@ -7207,6 +7243,7 @@ s,@host@,$host,;t t
 s,@host_cpu@,$host_cpu,;t t
 s,@host_vendor@,$host_vendor,;t t
 s,@host_os@,$host_os,;t t
+s,@CONFIG_EXPERIMENTAL@,$CONFIG_EXPERIMENTAL,;t t
 s,@CONFIG_CXXDIALECT@,$CONFIG_CXXDIALECT,;t t
 s,@CONFIG_OS@,$CONFIG_OS,;t t
 s,@CONFIG_OS_SUFFIX@,$CONFIG_OS_SUFFIX,;t t
