Adapted configure.in for Imlib2 plug-in

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -852,6 +852,7 @@ Optional Packages:
   --with-x                use the X Window System
   --with-iconv=DIR        where to find iconv system
   --with-freetype=ARG     with freetype support ARG=linked
+  --with-imlib2=ARG     with imlib2 support ARG=linked
 
 Some influential environment variables:
   CC          C compiler command
@@ -5148,6 +5149,200 @@ LIBS="$SAVE_LIBS"
 
 
 #--------------------------------------------------------------------
+# Checks for Imlib2
+#--------------------------------------------------------------------
+
+
+# Check whether --with-imlib2 or --without-imlib2 was given.
+if test "${with_imlib2+set}" = set; then
+  withval="$with_imlib2"
+
+fi;
+
+SAVE_CPPFLAGS="$CPPFLAGS"
+SAVE_LDFLAGS="$LDFLAGS"
+SAVE_LIBS="$LIBS"
+CONFIG_USE_IMLIB2=""
+if test "$with_imlib2" = "no" ; then
+    echo "$as_me:$LINENO: result: disabling imlib2 support" >&5
+echo "${ECHO_T}disabling imlib2 support" >&6
+else
+    CPPFLAGS=`imlib2-config --cflags`
+    LIBS=`imlib2-config --libs`
+    if test "${ac_cv_header_ft2build_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for ft2build.h" >&5
+echo $ECHO_N "checking for ft2build.h... $ECHO_C" >&6
+if test "${ac_cv_header_ft2build_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_ft2build_h" >&5
+echo "${ECHO_T}$ac_cv_header_ft2build_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking ft2build.h usability" >&5
+echo $ECHO_N "checking ft2build.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+$ac_includes_default
+#include <ft2build.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking ft2build.h presence" >&5
+echo $ECHO_N "checking ft2build.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <ft2build.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: ft2build.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: ft2build.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ft2build.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: ft2build.h: proceeding with the preprocessor's result" >&2;};;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: ft2build.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: ft2build.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ft2build.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: ft2build.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: ft2build.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: ft2build.h: proceeding with the preprocessor's result" >&2;};;
+esac
+echo "$as_me:$LINENO: checking for ft2build.h" >&5
+echo $ECHO_N "checking for ft2build.h... $ECHO_C" >&6
+if test "${ac_cv_header_ft2build_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_ft2build_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_ft2build_h" >&5
+echo "${ECHO_T}$ac_cv_header_ft2build_h" >&6
+
+fi
+if test $ac_cv_header_ft2build_h = yes; then
+  echo "$as_me:$LINENO: checking for imlib2" >&5
+echo $ECHO_N "checking for imlib2... $ECHO_C" >&6
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <X11/Xlib.h>
+#include <Imlib2.h>
+#include <stdio.h>
+#include <string.h>
+
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+    Imlib_Image image= imlib_load_image("");
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    CONFIG_USE_IMLIB2="#define USE_IMLIB2"
+    IMLIB2_CFLAGS="$CPPFLAGS"
+    if test "$with_imlib2" = "linked" -o "$with_imlib2" = "" ; then
+      IMLIB2_LDFLAGS="$LIBS"
+      CONFIG_LINKED_IMLIB2="#define LINKED_IMLIB2"
+    fi
+
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+
+
+fi
+
+CPPFLAGS="$SAVE_CPPFLAGS"
+LDFLAGS="$SAVE_LDFLAGS"
+LIBS="$SAVE_LIBS"
+
+
+
+
+
+
+#--------------------------------------------------------------------
 # Checks for library functions
 #--------------------------------------------------------------------
 
@@ -7004,6 +7199,10 @@ s,@CONFIG_USE_FREETYPE@,$CONFIG_USE_FREETYPE,;t t
 s,@CONFIG_LINKED_FREETYPE@,$CONFIG_LINKED_FREETYPE,;t t
 s,@FREETYPE_CFLAGS@,$FREETYPE_CFLAGS,;t t
 s,@FREETYPE_LDFLAGS@,$FREETYPE_LDFLAGS,;t t
+s,@CONFIG_USE_IMLIB2@,$CONFIG_USE_IMLIB2,;t t
+s,@CONFIG_LINKED_IMLIB2@,$CONFIG_LINKED_IMLIB2,;t t
+s,@IMLIB2_CFLAGS@,$IMLIB2_CFLAGS,;t t
+s,@IMLIB2_LDFLAGS@,$IMLIB2_LDFLAGS,;t t
 s,@CONFIG_GET_TIME_OF_DAY@,$CONFIG_GET_TIME_OF_DAY,;t t
 s,@CONFIG_DOTS@,$CONFIG_DOTS,;t t
 s,@CONFIG_GUILE_STR_SIZE_T@,$CONFIG_GUILE_STR_SIZE_T,;t t
