Cairo renderer

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -681,6 +681,8 @@ ICONV_CFLAGS
 ICONV_LDFLAGS
 FREETYPE_CFLAGS
 FREETYPE_LDFLAGS
+CAIRO_CFLAGS
+CAIRO_LDFLAGS
 IMLIB2_CFLAGS
 IMLIB2_LDFLAGS
 AXEL_CFLAGS
@@ -1356,6 +1358,7 @@ Optional Packages:
   --with-x                use the X Window System
   --with-iconv=DIR        where to find iconv system
   --with-freetype=ARG     with freetype support ARG=linked
+  --with-cairo=ARG        with cairo support ARG=no
   --with-imlib2=ARG       with imlib2 support ARG=no
   --with-axel=ARG       with axel support ARG=no
   --with-qt               Path to Qt [Look in PATH and /usr/local/Trolltech]
@@ -6965,6 +6968,233 @@ LIBS="$SAVE_LIBS"
 
 
 #--------------------------------------------------------------------
+# Checks for Cairo library
+#--------------------------------------------------------------------
+
+
+# Check whether --with-cairo was given.
+if test "${with_cairo+set}" = set; then
+  withval=$with_cairo;
+fi
+
+
+SAVE_CPPFLAGS="$CPPFLAGS"
+SAVE_LDFLAGS="$LDFLAGS"
+SAVE_LIBS="$LIBS"
+if test "$with_cairo" = "no" -o "$with_cairo" = "" ; then
+    { echo "$as_me:$LINENO: result: disabling cairo support" >&5
+echo "${ECHO_T}disabling cairo support" >&6; }
+else
+    CPPFLAGS=`pkg-config --cflags cairo`
+    LIBS=`pkg-config --libs cairo`
+    if test "${ac_cv_header_cairo_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for cairo.h" >&5
+echo $ECHO_N "checking for cairo.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_cairo_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_cairo_h" >&5
+echo "${ECHO_T}$ac_cv_header_cairo_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking cairo.h usability" >&5
+echo $ECHO_N "checking cairo.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <cairo.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking cairo.h presence" >&5
+echo $ECHO_N "checking cairo.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <cairo.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: cairo.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: cairo.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: cairo.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: cairo.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: cairo.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: cairo.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: cairo.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: cairo.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: cairo.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: cairo.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: cairo.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: cairo.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: cairo.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: cairo.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: cairo.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: cairo.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for cairo.h" >&5
+echo $ECHO_N "checking for cairo.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_cairo_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_cairo_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_cairo_h" >&5
+echo "${ECHO_T}$ac_cv_header_cairo_h" >&6; }
+
+fi
+if test $ac_cv_header_cairo_h = yes; then
+  { echo "$as_me:$LINENO: checking for cairo" >&5
+echo $ECHO_N "checking for cairo... $ECHO_C" >&6; }
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <cairo.h>
+
+int
+main ()
+{
+
+    cairo_surface_t *surface;
+    surface = cairo_image_surface_create (CAIRO_FORMAT_ARGB32, 120, 120);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_CAIRO 1
+_ACEOF
+
+    CAIRO_CFLAGS="$CPPFLAGS"
+    if test "$with_cairo" = "linked" ; then
+      CAIRO_LDFLAGS="$LIBS"
+
+cat >>confdefs.h <<\_ACEOF
+#define LINKED_CAIRO 1
+_ACEOF
+
+    fi
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+
+
+fi
+
+CPPFLAGS="$SAVE_CPPFLAGS"
+LDFLAGS="$SAVE_LDFLAGS"
+LIBS="$SAVE_LIBS"
+
+
+
+
+#--------------------------------------------------------------------
 # Checks for Imlib2 library
 #--------------------------------------------------------------------
 
@@ -9874,6 +10104,8 @@ ICONV_CFLAGS!$ICONV_CFLAGS$ac_delim
 ICONV_LDFLAGS!$ICONV_LDFLAGS$ac_delim
 FREETYPE_CFLAGS!$FREETYPE_CFLAGS$ac_delim
 FREETYPE_LDFLAGS!$FREETYPE_LDFLAGS$ac_delim
+CAIRO_CFLAGS!$CAIRO_CFLAGS$ac_delim
+CAIRO_LDFLAGS!$CAIRO_LDFLAGS$ac_delim
 IMLIB2_CFLAGS!$IMLIB2_CFLAGS$ac_delim
 IMLIB2_LDFLAGS!$IMLIB2_LDFLAGS$ac_delim
 AXEL_CFLAGS!$AXEL_CFLAGS$ac_delim
@@ -9900,8 +10132,6 @@ QT_CXXFLAGS!$QT_CXXFLAGS$ac_delim
 QT_INCPATH!$QT_INCPATH$ac_delim
 QT_CPPFLAGS!$QT_CPPFLAGS$ac_delim
 QT_LFLAGS!$QT_LFLAGS$ac_delim
-QT_LDFLAGS!$QT_LDFLAGS$ac_delim
-QT_LIBS!$QT_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -9943,6 +10173,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+QT_LDFLAGS!$QT_LDFLAGS$ac_delim
+QT_LIBS!$QT_LIBS$ac_delim
 X11_CFLAGS!$X11_CFLAGS$ac_delim
 X11_LDFLAGS!$X11_LDFLAGS$ac_delim
 COCOA_CFLAGS!$COCOA_CFLAGS$ac_delim
@@ -9986,7 +10218,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 41; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 43; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
